### ISSUE TITLE
implement classifier based on logistic regression

### ISSUE THREAD

**Issue by BenjaminBlankertz** [bbci/bbci_public#74] opened 2015-06-10 09:08 UTC

**Comment by MihailBogojeski** [comment] 2015-06-17 12:35
I could take this issue, since I already implemented a logistic regression classifier as the top level classifier for HLDA. I believe most of the code can be reused. Any specifics on the signatures?

**Comment by BenjaminBlankertz** [comment] 2015-06-19 18:54
Yes, take it. That would be great. Signature should be the same as for other classifiers. If the function takes optional arguments. see train_SWLDAmatlab.m.

**Comment by svendaehne** [comment] 2015-10-28 17:44
closed by merge #104

**Closed as completed by svendaehne** 2015-10-28 17:44 UTC
Labels: claimed
